# GitHub Funding / Sponsor Configuration
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

buy_me_a_coffee: mdtazmir
custom: ['https://buymeacoffee.com/mdtazmir']
